# Project Information
site_name: EDA Wiki
site_description: EDA Wiki是关于EDA算法和开源工具的协作文档
site_author: EDA Wiki Team
site_url: https://openbelt.org.cn/wiki/
strict: true

# Repository
repo_name: 'pkuzjx/EDA-wiki'
repo_url: 'https://github.com/pkuzjx/EDA-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'ICP备案号：<a href="http://www.beian.gov.cn">京ICP备19041147号</a> <br> Copyright &copy; 2019 - 2019 EDA Wiki Team'
google_analytics:
  - ''
  - 'auto'

# Contents
nav:
  - 简介:
    - Getting started: index.md
    - 关于本项目: intro/about.md
    - EDA课程与教程: intro/course.md
    - 开源EDA研讨会: intro/workshop.md
    - 致谢: intro/thanks.md

  - 设计流程:
    - 设计流程简介: flow/index.md
    - ASIC流程: flow/asic.md
    - FPGA流程: flow/fpga.md
    - 标准格式: flow/standard.md
    - DSL: flow/dsl.md
    - IR: flow/ir.md

  - 设计综合:
    - 设计综合简介: synthesis/index.md
    - 高层综合: synthesis/behavior.md
    - 逻辑综合: synthesis/logic.md
    - 布局布线: synthesis/par.md
    - 版图综合: synthesis/layout.md

  - 测试与验证:
    - 测试与验证简介: verification/index.md
    - 测试: verification/testing.md
    - 形式化验证: verification/formal.md
    - DRC: verification/drc.md
    - LVS: verification/lvs.md

  - 分析与建模:
    - 分析与建模简介: analysis/index.md
    - 逻辑仿真: analysis/logic.md
    - 时序分析: analysis/timing.md
    - 电路分析: analysis/circuit.md
    - 物理分析: analysis/physics.md

  - 硅知产:
    - 硅知产简介: sip/index.md
    - PDK与单元库: sip/pdk.md
    - 存储单元: sip/mem.md
    - 通用计算: sip/general.md
    - 专用计算: sip/special.md
    - 可重构计算: sip/reconfig.md
    - 片上互连: sip/interconn.md
    - 输入输出: sip/inout.md
    - 传感器: sip/sensor.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  #favicon: 'favicon.ico'

  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  # disqus: 'EDA-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''

extra_javascript:
  - '_static/js/extra.js?v=15'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'


extra_css:
  - '_static/css/extra.css?v=12'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_truly_sane_lists
